/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crossroad.view;

import crossroad.Main;

/**
 *
 * @author Lucas F. Vidigal
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setEnabled(true);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonOnline = new javax.swing.JButton();
        jButtonOffline = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonOnline.setText("Online");
        jButtonOnline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOnlineActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOnline, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        jButtonOffline.setText("Offline");
        jButtonOffline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOfflineActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOffline, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 401, 235));

        setSize(new java.awt.Dimension(417, 274));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOnlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOnlineActionPerformed
        
        new SetBackGround(1);
        this.dispose();
    }//GEN-LAST:event_jButtonOnlineActionPerformed

    private void jButtonOfflineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOfflineActionPerformed
        
        new SetBackGround(0);
        this.dispose();
    }//GEN-LAST:event_jButtonOfflineActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOffline;
    private javax.swing.JButton jButtonOnline;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
